### ISSUE TITLE
Fix conda package

### ISSUE THREAD

**Issue by jepegit** [jepegit/cellpy#333]
Installing mamba/conda package of cellpy 1.0.2 for python 3.12 must be checked and fixed.

**Comment by jepegit** [comment]
The issue seems to be the conda recipe - it does not automatically update the python restrictions based on the pypi release. 
```
build:
  number: 0
  skip: true  # [py<310 or py>311]
  entry_points:
    - cellpy=cellpy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
```

Change to:

```
build:
  number: 0
  skip: true  # [py<310 or py>313]
  entry_points:
    - cellpy=cellpy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
```
