### ISSUE TITLE
Instrument set in config not respected by cellpy

### ISSUE THREAD

**Issue by jepegit** [jepegit/cellpy#337]

**Comment by jepegit** [comment]
Set the default instrument like this (example for neware text or csv with the model "one"):

```yaml
Instruments:
  tester: neware_txt
  ...

  Neware:
      default_model: one
```
